---
# vim: set ft=yaml.ansible:

- name: Prepare to be able to install packages
  ansible.builtin.import_tasks: prepare.yml

- name: Handle APT keys first
  ansible.builtin.import_tasks: keys.yml

- name: Handle APT repositories
  ansible.builtin.import_tasks: repositories.yml

## Installs
- name: APT packages
  ansible.builtin.import_tasks: packages_apt.yml

- name: Deb packages
  ansible.builtin.import_tasks: packages_deb.yml

- name: Snap packages
  ansible.builtin.import_tasks: packages_snap.yml

- name: Flatpak packages
  ansible.builtin.import_tasks: packages_flatpak.yml

## Finally, the removals (should always be last)
- name: Package removals and exclusions
  ansible.builtin.import_tasks: removals.yml
