---
# vim: set ft=yaml.ansible:

### Install deb files
- name: Install deb packages ( "{{ install_apps_package_set }}" )
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ install_apps_deb_packages }}"
