---
# vim: set ft=yaml.ansible:

### Install tools needed for the other install methods
- name: Install requirements for installation support ( "{{ install_apps_package_set }}" )
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - flatpak
    - curl
    - python3-requests
    - fuse3
    - squashfuse

- name: Install snapd ( "{{ install_apps_package_set }}" )
  become: true
  ansible.builtin.apt:
    name: snapd
  register: install_apps_snapd_installed

- name: Enable the snapd service ( "{{ install_apps_package_set }}" )
  become: true
  ansible.builtin.service:
    name: snapd.socket
    enabled: true

- name: Reboot (required for snapd) ( "{{ install_apps_package_set }}" )
  become: true
  ansible.builtin.reboot: null
  when: install_apps_snapd_installed.changed

- name: Install flathub Flatpak repository ( "{{ install_apps_package_set }}" )
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
