---
# vim: set ft=yaml.ansible :

- name: Add Vagrant user to the default groups
  become: true
  ansible.builtin.user:
    name: vagrant
    groups: "{{ item }}"
    append: true
  with_items:
    - audio
    - video
    - plugdev
    - netdev
    - sudo
    - _ssh
    - users

- name: Gather group information
  ansible.builtin.getent:
    database: group
    split: ":"

- name: Add vagrant user to the data-user group
  become: true
  ansible.builtin.user:
    name: vagrant
    groups: data-user
    append: true
  when: ansible_facts.getent_group["data-user"] != None

- name: Add Vagrant user to the Virtualbox Group
  become: true
  ansible.builtin.user:
    name: vagrant
    groups: vboxsf
    append: true
  when: ansible_virtualization_type == "virtualbox"
    and ansible_virtualization_role == "guest"

- name: Setup vagrant user for passwordless sudo
  become: true
  ansible.builtin.template:
    src: etc-sudoers.d--vagrant.j2
    dest: /etc/sudoers.d/vagrant
    owner: root
    group: root
    mode: "0640"
    backup: false

- name: Add users to the vagrant group (to allow access to vagrant share)
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: vagrant
    append: true
  loop: "{{ virtualbox_guest_vagrant_users }}"
