---
# vim: set ft=yaml.ansible:

## Drivers & Firmware
- name: Install Drivers And Firmware
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - amd64-microcode
      - intel-microcode
      - firmware-iwlwifi
      - firmware-realtek
      - bluez-firmware
      - task-laptop

- name: Install Core Packages
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - tmux
      - git
      - git-doc
      - exuberant-ctags
      - vim-doc
      - vim-nox
      - atool
      - dtrx
      - rcm
      - golang
      - gfortran
      - ripgrep
      - arc
      - arj
      - lzip
      - lzop
      - unace
      - unalz
      - unrar
      - alien
      - lzma
      - p7zip-rar
      - parted
      - fuse3
      - pipx
      - rename
      - mediainfo
      - inxi
      - uuid
      - sshfs
      - cgroupfs-mount
      - dnsutils

- name: Install Firmware Update Utility
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - fwupd
      - fwupd-amd64-signed
      - fwupd-doc

- name: Install Yubikey (FIDO2) support
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - libfido2-1
      - libfido2-dev
      - libfido2-doc
      - fido2-tools

- name: Install Build Dependencies For ASDF
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - libssl-dev
      - libssh-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
      - gnutls-bin
      - libmpfr-dev
      - dns-root-data
      - libhidapi-libusb0
      - libxcb-xinerama0
      - libyaml-dev

- name: Install Dependencies For Neovim
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - fortunes
      - fortune-mod
      - luarocks
      - cmake
      - cmake-format

- name: Install MooseFS client
  become: true
  ansible.builtin.apt:
    state: present
    name: moosefs-client

- name: Install Distribution Specific Packages (Ubuntu)
  become: true
  ansible.builtin.apt:
    state: present
    name: ubuntu-restricted-extras
  when: ansible_distribution == "Ubuntu"
