---
# vim: set ft=yaml.ansible:

- name: Install font utilities and prerequisites
  become: true
  ansible.builtin.apt:
    name: fontconfig

- name: Install fonts from packages
  become: true
  ansible.builtin.apt:
    name: "{{ font_packages }}"

- name: Install fonts from URL (system)
  ansible.builtin.include_tasks:
    file: install-font-from-url.yml
  loop: "{{ url_fonts_system }}"
  vars:
    install_fonts_url: "{{ item.url }}" # noqa: var-naming[no-role-prefix]
    install_fonts_file: "{{ item.file }}"
    install_fonts_folder: "{{ item.folder | default('ansible') }}"

- name: Install fonts from URL (user)
  ansible.builtin.include_tasks:
    file: install-font-from-url.yml
  loop: "{{ url_fonts_user }}"
  vars:
    install_fonts_url: "{{ item.url }}" # noqa: var-naming[no-role-prefix]
    install_fonts_file: "{{ item.file }}"
    install_fonts_folder: "{{ item.folder | default('ansible') }}"
    install_fonts_user: "{{ item.user }}"
