---
# vim: set ft=yaml.ansible:

- name: Upgrade (Full)
  hosts: '{{targets|default("all")}}'
  gather_facts: false

  tasks:
    - name: Update the package cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade the packages
      become: true
      ansible.builtin.apt:
        upgrade: "{{ apt_upgrade_level | default(full) }}"
